# Generated by Django 3.2.2 on 2021-05-06 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('no', models.CharField(blank=True, max_length=15, null=True, verbose_name='번호')),
                ('sentence', models.CharField(blank=True, max_length=100, null=True, verbose_name='문장')),
                ('passage', models.TextField()),
                ('topic', models.CharField(blank=True, max_length=100, null=True, verbose_name='토픽')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='카테고리')),
                ('source', models.CharField(blank=True, max_length=20, null=True, verbose_name='출처')),
            ],
            options={
                'verbose_name': '문장',
                'verbose_name_plural': '문장',
                'db_table': 'mrc_passage',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성일시')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('no', models.CharField(blank=True, max_length=15, null=True, verbose_name='번호')),
                ('question', models.TextField(blank=True, max_length=100, null=True, verbose_name='질문')),
                ('answer', models.CharField(blank=True, max_length=100, null=True, verbose_name='답')),
                ('s_pos', models.IntegerField(blank=True, null=True, verbose_name='시작위치')),
                ('e_pos', models.IntegerField(blank=True, null=True, verbose_name='종료위치')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrc.passage')),
            ],
            options={
                'verbose_name': '질문',
                'verbose_name_plural': '질문',
                'db_table': 'mrc_question',
                'ordering': ['passage__no', 'no'],
                'managed': True,
            },
        ),
    ]
